/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/umbraco/delivery/api/v2/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContent2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/content/item/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContentItemByPath2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/content/item/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContentItemById2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/content/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContentItems2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMedia2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media/item/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMediaItemByPath2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media/item/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMediaItemById2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMediaItems2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiBlockGridAreaModel: {
            alias: string;
            /** Format: int32 */
            rowSpan: number;
            /** Format: int32 */
            columnSpan: number;
            items: components["schemas"]["ApiBlockGridItemModel"][];
        };
        ApiBlockGridItemModel: components["schemas"]["ApiBlockItemModel"] & {
            /** Format: int32 */
            rowSpan?: number;
            /** Format: int32 */
            columnSpan?: number;
            /** Format: int32 */
            areaGridColumns?: number;
            areas?: components["schemas"]["ApiBlockGridAreaModel"][];
        };
        ApiBlockItemModel: {
            content: components["schemas"]["IApiElementModel"];
            settings?: components["schemas"]["IApiElementModel"];
        };
        ApiBlockListModel: {
            items: (components["schemas"]["ApiBlockItemModel"] | components["schemas"]["ApiBlockGridItemModel"])[];
        };
        ApiContentRouteModel: {
            path: string;
            queryString?: string | null;
            startItem: components["schemas"]["ApiContentStartItemModel"];
        };
        ApiContentStartItemModel: {
            /** Format: uuid */
            id: string;
            path: string;
        };
        ApiLinkModel: {
            readonly url?: string | null;
            readonly queryString?: string | null;
            readonly title?: string | null;
            readonly target?: string | null;
            /** Format: uuid */
            readonly destinationId?: string | null;
            readonly destinationType?: string | null;
            readonly route?: components["schemas"]["ApiContentRouteModel"] | null;
            linkType: components["schemas"]["LinkTypeModel"];
        };
        AppreciationBlockElementModel: {
            properties?: components["schemas"]["AppreciationBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "appreciationBlock";
        });
        AppreciationBlockPropertiesModel: Record<string, never>;
        COm_SeoContentModel: {
            properties?: components["schemas"]["COm_SeoPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_SEO";
        });
        COm_SeoContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["COm_SeoContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_SEO";
        };
        COm_SeoPropertiesModel: {
            pageBrowserTitle?: string | null;
            metaDescription?: string | null;
            metaKeywords?: string | null;
            socialMediaTitle?: string | null;
            socialMediaImage?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
            socialMediaDescription?: string | null;
            blockThisPageFromSearchEngines?: boolean | null;
            blockThisPageAndAllSubPagesFromSearchEngines?: boolean | null;
            canonicalURL?: string | null;
        };
        COm_footerContentModel: {
            properties?: components["schemas"]["COm_footerPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_footer";
        });
        COm_footerContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["COm_footerContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_footer";
        };
        COm_footerPropertiesModel: {
            footerLogo?: string | null;
            description?: string | null;
            footerMenu?: components["schemas"]["ApiLinkModel"][] | null;
            copyright?: string | null;
            footerMarquee?: string | null;
        };
        COm_headerElementModel: {
            properties?: components["schemas"]["COm_headerPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_header";
        });
        COm_headerPropertiesModel: {
            logo?: string | null;
            navMenu?: components["schemas"]["ApiLinkModel"][] | null;
        };
        COm_scriptsContentModel: {
            properties?: components["schemas"]["COm_scriptsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_scripts";
        });
        COm_scriptsContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["COm_scriptsContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_scripts";
        };
        COm_scriptsPropertiesModel: {
            headerScripts?: string | null;
            bodyScripts?: string | null;
            footerScripts?: string | null;
        };
        COm_searchSettingsContentModel: {
            properties?: components["schemas"]["COm_searchSettingsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_searchSettings";
        });
        COm_searchSettingsContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["COm_searchSettingsContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_searchSettings";
        };
        COm_searchSettingsPropertiesModel: {
            /** Format: int32 */
            searchPage?: number | null;
            /** Format: int32 */
            pageItemCount?: number | null;
        };
        COm_settingsContentModel: {
            properties?: components["schemas"]["COm_settingsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_settings";
        });
        COm_settingsContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["COm_settingsContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_settings";
        };
        COm_settingsPropertiesModel: {
            websiteName?: string | null;
            hideFromSearch?: boolean | null;
            menuTitle?: string | null;
            umbracoUrlName?: string | null;
            umbracoUrlAlias?: string | null;
            umbracoRedirect?: components["schemas"]["IApiContentModel"];
            umbracoInternalRedirectId?: components["schemas"]["IApiContentModel"];
            externalRedirect?: string | null;
        };
        COm_siteSettingsContentModel: {
            properties?: components["schemas"]["COm_siteSettingsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_siteSettings";
        });
        COm_siteSettingsContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["COm_siteSettingsContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_siteSettings";
        };
        COm_siteSettingsPropertiesModel: {
            fldWebsiteName?: string | null;
            fldFavicon?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
        };
        COm_socialLinksContentModel: {
            properties?: components["schemas"]["COm_socialLinksPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_socialLinks";
        });
        COm_socialLinksContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["COm_socialLinksContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "cOM_socialLinks";
        };
        COm_socialLinksPropertiesModel: {
            discord?: components["schemas"]["ApiLinkModel"][] | null;
            meetup?: components["schemas"]["ApiLinkModel"][] | null;
            gitHub?: components["schemas"]["ApiLinkModel"][] | null;
            youtube?: components["schemas"]["ApiLinkModel"][] | null;
            linkedin?: components["schemas"]["ApiLinkModel"][] | null;
        };
        ContactUsElementModel: {
            properties?: components["schemas"]["ContactUsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "contactUs";
        });
        ContactUsPropertiesModel: {
            title?: string | null;
        };
        CountdownElementModel: {
            properties?: components["schemas"]["CountdownPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "countdown";
        });
        CountdownPropertiesModel: {
            countdownSubtitle?: string | null;
            session?: string | null;
            /** Format: date-time */
            timer?: string | null;
        };
        EventContentModel: {
            properties?: components["schemas"]["EventPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "event";
        });
        EventContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["EventContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "event";
        };
        EventPropertiesModel: {
            eventTitle?: string | null;
            eventType?: string | null;
            speaker?: components["schemas"]["IApiContentModel"];
            /** Format: date-time */
            dateAndTime?: string | null;
            status?: string | null;
            colors?: string | null;
        } & (components["schemas"]["COm_SeoPropertiesModel"] & components["schemas"]["COm_settingsPropertiesModel"] & components["schemas"]["XmlSiteMapSettingsPropertiesModel"]);
        EventsContentModel: {
            properties?: components["schemas"]["EventsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "events";
        });
        EventsContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["EventsContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "events";
        };
        EventsPropertiesModel: components["schemas"]["COm_SeoPropertiesModel"] & components["schemas"]["COm_settingsPropertiesModel"] & components["schemas"]["XmlSiteMapSettingsPropertiesModel"];
        FaqElementModel: {
            properties?: components["schemas"]["FaqPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "faq";
        });
        FaqPropertiesModel: {
            title?: string | null;
            faqBlocks?: components["schemas"]["ApiBlockListModel"];
            titleCard?: string | null;
            titleDescription?: string | null;
            tipOfTheDay?: string | null;
        };
        FaqSubBlockElementModel: {
            properties?: components["schemas"]["FaqSubBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "faqSubBlock";
        });
        FaqSubBlockPropertiesModel: {
            question?: string | null;
            answer?: components["schemas"]["RichTextModel"];
        };
        FeaturesElementModel: {
            properties?: components["schemas"]["FeaturesPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "features";
        });
        FeaturesPropertiesModel: {
            headingOne?: string | null;
            descriptionOne?: string | null;
            headingSecond?: string | null;
            descriptionSecond?: string | null;
            headingThird?: string | null;
            descriptionThird?: string | null;
        };
        GalleryElementModel: {
            properties?: components["schemas"]["GalleryPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "gallery";
        });
        GalleryPropertiesModel: {
            title?: string | null;
            media?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
        };
        GoldElementModel: {
            properties?: components["schemas"]["GoldPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "gold";
        });
        GoldPropertiesModel: {
            companyName?: string | null;
            description?: string | null;
        };
        HeroElementModel: {
            properties?: components["schemas"]["HeroPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "hero";
        });
        HeroPropertiesModel: {
            heroSubtitle?: string | null;
            heroTitle?: string | null;
            heroCaptionText?: string | null;
            heroCaptionButton?: components["schemas"]["ApiLinkModel"][] | null;
            slideLabel?: string | null;
            slideLabelTwo?: string | null;
            slideImage?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
            upcomingSession?: components["schemas"]["IApiContentModel"];
        };
        HomeContentModel: {
            properties?: components["schemas"]["HomePropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "home";
        });
        HomeContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["HomeContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "home";
        };
        HomePropertiesModel: {
            mainContent?: components["schemas"]["ApiBlockListModel"];
        } & (components["schemas"]["COm_SeoPropertiesModel"] & components["schemas"]["COm_settingsPropertiesModel"] & components["schemas"]["XmlSiteMapSettingsPropertiesModel"]);
        HttpValidationProblemDetails: components["schemas"]["ProblemDetails"] & ({
            errors?: {
                [key: string]: string[];
            };
        } & {
            [key: string]: unknown;
        });
        IApiContentModel: components["schemas"]["COm_scriptsContentModel"] | components["schemas"]["COm_searchSettingsContentModel"] | components["schemas"]["COm_SeoContentModel"] | components["schemas"]["COm_settingsContentModel"] | components["schemas"]["COm_socialLinksContentModel"] | components["schemas"]["XmlSiteMapSettingsContentModel"] | components["schemas"]["COm_siteSettingsContentModel"] | components["schemas"]["COm_footerContentModel"] | components["schemas"]["HomeContentModel"] | components["schemas"]["SpeakersContentModel"] | components["schemas"]["SpeakerContentModel"] | components["schemas"]["EventsContentModel"] | components["schemas"]["EventContentModel"] | components["schemas"]["ProjectsContentModel"] | components["schemas"]["ProjectContentModel"] | components["schemas"]["SiteSettingsContentModel"];
        IApiContentModelBase: {
            /** Format: uuid */
            readonly id: string;
            readonly contentType: string;
            readonly name?: string | null;
            /** Format: date-time */
            readonly createDate: string;
            /** Format: date-time */
            readonly updateDate: string;
            readonly route: components["schemas"]["ApiContentRouteModel"];
        } & Omit<WithRequired<components["schemas"]["IApiElementModelBase"], "contentType" | "id">, "contentType">;
        IApiContentResponseModel: components["schemas"]["COm_scriptsContentResponseModel"] | components["schemas"]["COm_searchSettingsContentResponseModel"] | components["schemas"]["COm_SeoContentResponseModel"] | components["schemas"]["COm_settingsContentResponseModel"] | components["schemas"]["COm_socialLinksContentResponseModel"] | components["schemas"]["XmlSiteMapSettingsContentResponseModel"] | components["schemas"]["COm_siteSettingsContentResponseModel"] | components["schemas"]["COm_footerContentResponseModel"] | components["schemas"]["HomeContentResponseModel"] | components["schemas"]["SpeakersContentResponseModel"] | components["schemas"]["SpeakerContentResponseModel"] | components["schemas"]["EventsContentResponseModel"] | components["schemas"]["EventContentResponseModel"] | components["schemas"]["ProjectsContentResponseModel"] | components["schemas"]["ProjectContentResponseModel"] | components["schemas"]["SiteSettingsContentResponseModel"];
        IApiContentResponseModelBase: {
            /** Format: uuid */
            readonly id: string;
            readonly contentType: string;
            readonly name?: string | null;
            /** Format: date-time */
            readonly createDate: string;
            /** Format: date-time */
            readonly updateDate: string;
            readonly route: components["schemas"]["ApiContentRouteModel"];
            readonly cultures: {
                [key: string]: components["schemas"]["ApiContentRouteModel"];
            };
        } & Omit<WithRequired<components["schemas"]["IApiContentModelBase"], "contentType" | "createDate" | "id" | "route" | "updateDate">, "contentType">;
        IApiElementModel: components["schemas"]["COm_headerElementModel"] | components["schemas"]["HeroElementModel"] | components["schemas"]["MarqueeElementModel"] | components["schemas"]["MarqueeReverseElementModel"] | components["schemas"]["CountdownElementModel"] | components["schemas"]["FeaturesElementModel"] | components["schemas"]["LatestEventsElementModel"] | components["schemas"]["SpeakersElementElementModel"] | components["schemas"]["ProjectsShowcaseElementModel"] | components["schemas"]["SponsorsElementModel"] | components["schemas"]["PlatinumElementModel"] | components["schemas"]["GoldElementModel"] | components["schemas"]["Platinum1ElementModel"] | components["schemas"]["GalleryElementModel"] | components["schemas"]["AppreciationBlockElementModel"] | components["schemas"]["FaqSubBlockElementModel"] | components["schemas"]["FaqElementModel"] | components["schemas"]["ContactUsElementModel"];
        IApiElementModelBase: {
            /** Format: uuid */
            readonly id: string;
            readonly contentType: string;
        };
        IApiMediaWithCropsModel: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly mediaType: string;
            readonly url: string;
            readonly extension?: string | null;
            /** Format: int32 */
            readonly width?: number | null;
            /** Format: int32 */
            readonly height?: number | null;
            /** Format: int32 */
            readonly bytes?: number | null;
            readonly properties: {
                [key: string]: unknown;
            };
            focalPoint?: components["schemas"]["ImageFocalPointModel"];
            readonly crops?: components["schemas"]["ImageCropModel"][] | null;
        };
        IApiMediaWithCropsResponseModel: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly mediaType: string;
            readonly url: string;
            readonly extension?: string | null;
            /** Format: int32 */
            readonly width?: number | null;
            /** Format: int32 */
            readonly height?: number | null;
            /** Format: int32 */
            readonly bytes?: number | null;
            readonly properties: {
                [key: string]: unknown;
            };
            focalPoint: components["schemas"]["ImageFocalPointModel"];
            readonly crops?: components["schemas"]["ImageCropModel"][] | null;
            readonly path: string;
            /** Format: date-time */
            readonly createDate: string;
            /** Format: date-time */
            readonly updateDate: string;
        };
        ImageCropCoordinatesModel: {
            /** Format: double */
            x1: number;
            /** Format: double */
            y1: number;
            /** Format: double */
            x2: number;
            /** Format: double */
            y2: number;
        };
        ImageCropModel: {
            alias?: string | null;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            coordinates?: components["schemas"]["ImageCropCoordinatesModel"];
        };
        ImageFocalPointModel: {
            /** Format: double */
            left: number;
            /** Format: double */
            top: number;
        };
        LatestEventsElementModel: {
            properties?: components["schemas"]["LatestEventsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "latestEvents";
        });
        LatestEventsPropertiesModel: {
            title?: string | null;
            moreButton?: components["schemas"]["ApiLinkModel"][] | null;
        };
        /** @enum {string} */
        LinkTypeModel: "Content" | "Media" | "External";
        MarqueeElementModel: {
            properties?: components["schemas"]["MarqueePropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "marquee";
        });
        MarqueePropertiesModel: {
            text?: string | null;
        };
        MarqueeReverseElementModel: {
            properties?: components["schemas"]["MarqueeReversePropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "marqueeReverse";
        });
        MarqueeReversePropertiesModel: {
            text?: string | null;
        };
        PagedIApiContentResponseModel: {
            /** Format: int64 */
            total: number;
            items: components["schemas"]["IApiContentResponseModel"][];
        };
        PagedIApiMediaWithCropsResponseModel: {
            /** Format: int64 */
            total: number;
            items: components["schemas"]["IApiMediaWithCropsResponseModel"][];
        };
        Platinum1ElementModel: {
            properties?: components["schemas"]["Platinum1PropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "platinum1";
        });
        Platinum1PropertiesModel: {
            companyName?: string | null;
        };
        PlatinumElementModel: {
            properties?: components["schemas"]["PlatinumPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "platinum";
        });
        PlatinumPropertiesModel: {
            companyName?: string | null;
            description?: string | null;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        ProjectContentModel: {
            contentType: "ProjectContentModel";
            properties?: components["schemas"]["ProjectPropertiesModel"];
        } & Omit<components["schemas"]["IApiContentModelBase"], "contentType">;
        ProjectContentResponseModel: {
            contentType: "ProjectContentResponseModel";
        } & (Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["ProjectContentModel"], "contentType">);
        ProjectPropertiesModel: {
            projectTitle?: string | null;
            client?: string | null;
            description?: string | null;
            image?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
            stack?: string[] | null;
            year?: string | null;
            url?: components["schemas"]["ApiLinkModel"][] | null;
        } & (components["schemas"]["COm_SeoPropertiesModel"] & components["schemas"]["COm_settingsPropertiesModel"] & components["schemas"]["XmlSiteMapSettingsPropertiesModel"]);
        ProjectsContentModel: {
            contentType: "ProjectsContentModel";
            properties?: components["schemas"]["ProjectsPropertiesModel"];
        } & Omit<components["schemas"]["IApiContentModelBase"], "contentType">;
        ProjectsContentResponseModel: {
            contentType: "ProjectsContentResponseModel";
        } & (Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["ProjectsContentModel"], "contentType">);
        ProjectsPropertiesModel: components["schemas"]["COm_SeoPropertiesModel"] & components["schemas"]["COm_settingsPropertiesModel"] & components["schemas"]["XmlSiteMapSettingsPropertiesModel"];
        ProjectsShowcaseElementModel: {
            properties?: components["schemas"]["ProjectsShowcasePropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "projectsShowcase";
        });
        ProjectsShowcasePropertiesModel: {
            title?: string | null;
            projects?: components["schemas"]["IApiContentModel"];
            moreButton?: components["schemas"]["ApiLinkModel"][] | null;
            submissionHeading?: string | null;
            submissionDescription?: string | null;
            submissionButton?: components["schemas"]["ApiLinkModel"][] | null;
        };
        RichTextModel: {
            markup: string;
            blocks: (components["schemas"]["ApiBlockItemModel"] | components["schemas"]["ApiBlockGridItemModel"])[];
        };
        SiteSettingsContentModel: {
            contentType: "SiteSettingsContentModel";
            properties?: components["schemas"]["SiteSettingsPropertiesModel"];
        } & Omit<components["schemas"]["IApiContentModelBase"], "contentType">;
        SiteSettingsContentResponseModel: {
            contentType: "SiteSettingsContentResponseModel";
        } & (Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["SiteSettingsContentModel"], "contentType">);
        SiteSettingsPropertiesModel: components["schemas"]["COm_siteSettingsPropertiesModel"] & components["schemas"]["COm_footerPropertiesModel"] & components["schemas"]["COm_headerPropertiesModel"] & components["schemas"]["COm_socialLinksPropertiesModel"] & components["schemas"]["COm_scriptsPropertiesModel"];
        SpeakerContentModel: {
            contentType: "SpeakerContentModel";
            properties?: components["schemas"]["SpeakerPropertiesModel"];
        } & Omit<components["schemas"]["IApiContentModelBase"], "contentType">;
        SpeakerContentResponseModel: {
            contentType: "SpeakerContentResponseModel";
        } & (Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["SpeakerContentModel"], "contentType">);
        SpeakerPropertiesModel: {
            speakerName?: string | null;
            role?: string | null;
            company?: string | null;
            avatarImage?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
            bio?: string | null;
        } & (components["schemas"]["COm_SeoPropertiesModel"] & components["schemas"]["COm_settingsPropertiesModel"] & components["schemas"]["XmlSiteMapSettingsPropertiesModel"]);
        SpeakersContentModel: {
            contentType: "SpeakersContentModel";
            properties?: components["schemas"]["SpeakersPropertiesModel"];
        } & Omit<components["schemas"]["IApiContentModelBase"], "contentType">;
        SpeakersContentResponseModel: {
            contentType: "SpeakersContentResponseModel";
        } & (Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["SpeakersContentModel"], "contentType">);
        SpeakersElementElementModel: {
            properties?: components["schemas"]["SpeakersElementPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "speakersElement";
        });
        SpeakersElementPropertiesModel: {
            title?: string | null;
            speakers?: components["schemas"]["IApiContentModel"];
            moreButton?: components["schemas"]["ApiLinkModel"][] | null;
            heading?: string | null;
            description?: string | null;
            button?: components["schemas"]["ApiLinkModel"][] | null;
        };
        SpeakersPropertiesModel: components["schemas"]["COm_SeoPropertiesModel"] & components["schemas"]["COm_settingsPropertiesModel"] & components["schemas"]["XmlSiteMapSettingsPropertiesModel"];
        SponsorsElementModel: {
            properties?: components["schemas"]["SponsorsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "sponsors";
        });
        SponsorsPropertiesModel: {
            title?: string | null;
            sponsorsBlock?: components["schemas"]["ApiBlockListModel"];
            titleCta?: string | null;
            textCta?: string | null;
            buttonCta?: components["schemas"]["ApiLinkModel"][] | null;
        };
        XmlSiteMapSettingsContentModel: {
            contentType: "XmlSiteMapSettingsContentModel";
            properties?: components["schemas"]["XmlSiteMapSettingsPropertiesModel"];
        } & Omit<components["schemas"]["IApiContentModelBase"], "contentType">;
        XmlSiteMapSettingsContentResponseModel: {
            contentType: "XmlSiteMapSettingsContentResponseModel";
        } & (Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["XmlSiteMapSettingsContentModel"], "contentType">);
        XmlSiteMapSettingsPropertiesModel: {
            /** Format: int32 */
            searchEngineRelativePriority?: number | null;
            searchEngineChangeFrequency?: string | null;
            hideFromXmlSitemap?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "GetContent2.0": {
        parameters: {
            query?: {
                /** @description Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fetch?: string;
                /** @description Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                filter?: string[];
                /** @description Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                sort?: string[];
                /** @description Specifies the number of found content items to skip. Use this to control pagination of the response. */
                skip?: number;
                /** @description Specifies the number of found content items to take. Use this to control pagination of the response. */
                take?: number;
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedIApiContentResponseModel"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"] | components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetContentItemByPath2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiContentResponseModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetContentItemById2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiContentResponseModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetContentItems2.0": {
        parameters: {
            query?: {
                id?: string[];
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiContentResponseModel"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetMedia2.0": {
        parameters: {
            query?: {
                /** @description Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fetch?: string;
                /** @description Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                filter?: string[];
                /** @description Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                sort?: string[];
                /** @description Specifies the number of found media items to skip. Use this to control pagination of the response. */
                skip?: number;
                /** @description Specifies the number of found media items to take. Use this to control pagination of the response. */
                take?: number;
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedIApiMediaWithCropsResponseModel"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"] | components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    "GetMediaItemByPath2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiMediaWithCropsResponseModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetMediaItemById2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiMediaWithCropsResponseModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetMediaItems2.0": {
        parameters: {
            query?: {
                id?: string[];
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiMediaWithCropsResponseModel"][];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
